### ISSUE TITLE
Issue with Mongoid Inheritance

### ISSUE THREAD

**Issue by 3en** [collectiveidea/delayed_job_mongoid#12] opened 2011-06-14 04:44 UTC
There seems to be an issue with Mongoid Embedded 1-N (One to Many) Inheritance Classes (http://mongoid.org/docs/documents/inheritance.html) and Delayed_Job.

E.G

``` ruby

class User
  embeds_many :subscriptions

    def delay_test
      self.subscriptions.create!({},SubscriptionChild)
    end
end


class Subscription
  include Mongoid::Document

  embedded_in :user
end

class SubscriptionChild < Subscription
  # field goes here
end

```

Calling User.first.delay.delay_test results in a User#delay_test failed with NameError: uninitialized constant User::SubscriptionChild

Unless an embedded type/object of SubscriptionChild already exists in Subscription (user.subscriptions).

Seems like Delayed_Jobs worker isn't loading SubscriptionChild inherited class. Anyone know how to fix/hack around this?

**Comment by dblock** [comment] 2017-02-13 19:57
This is old. Doing some bookkeeping. Have you ever figured this out @3en? Should we close it?

**Comment by johnnyshields** [comment] 2022-04-01 12:11
I've tested this on Mongoid 7 and cannot reproduce. Seems to be specific to very old version of Mongoid (issue raised in 2011)

**Closed by johnnyshields** 2022-04-01 12:11 UTC
Labels: bug?, question
